name: Generate Stats, Trophies & Languages

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Stats Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: saifyali05
          filename: github-stats.svg
          base: header, activity, community

  trophies:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Trophies
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: saifyali05
          filename: github-trophies.svg
          base: ""
          plugin_trophies: yes
          plugin_trophies_theme: onedark

  languages:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Language Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: saifyali05
          filename: github-langs.svg
          base: header
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: no
          plugin_languages_details: bytes-size
